name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]  
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     
      - name: Checkout Code
        uses: actions/checkout@v3

      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies (Python)
        run: |
          pip install -r requirements.txt

      
      - name: Run Tests
        run: |
          echo "Running tests..."
          # pytest   (Python)
          # mvn test (Maven)
          # npm test (NodeJS)

      
      - name: Build Docker Image
        run: |
          docker build -t myapp:latest .

      
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker tag myapp:latest my-dockerhub-username/myapp:latest
          docker push my-dockerhub-username/myapp:latest

      
      - name: Deploy Step
        run: echo "Deployment step goes here"
